quarkus:
    http:
        port: 4000
    datasource:
        db-kind: postgresql
        db-version: 16.2
        username: postgres
        password: postgres
        jdbc:
            url: jdbc:postgresql://localhost:5432/quarkus
    hibernate-orm:
        schema-management:
            create-schemas: true
            strategy: validate # none, create, drop-and-create, drop, update, validate
        database:
            version-check:
                enabled: true
        log:
            sql: true
            format-sql: false
    rabbitmqclient:
        hostname: localhost
        port: 5672
        username: rabbitmq
        password: rabbitmq
        virtual-host: quarkus

app:
    name: "publisher"
